return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    bigfile = { enabled = true },
    notifier = { enabled = true },
    quickfile = { enabled = true },
    statuscolumn = { enabled = true },
    words = { enabled = true },
    lazygit = { enabled = true },
    terminal = { enabled = true },
    gitbrowse = { enabled = true },
    indent = { enabled = true },
    -- scroll = { enabled = true },
    zen = { enabled = true },
    rename = { enabled = true },
  },
  keys = {
    { "<c-y>", function() require("snacks").lazygit() end, desc = "Lazygit" },
    { "<leader>gg", function() require("snacks").lazygit() end, desc = "Lazygit" },
    { "<leader>gf", function() require("snacks").lazygit.log_file() end, desc = "Lazygit Current File" },
    { "<leader>gb", function() require("snacks").gitbrowse() end, desc = "Git Browse" },
    { "<c-/>", function() require("snacks").terminal() end, desc = "Toggle Terminal" },
    { "<leader>z", function() require("snacks").zen() end, desc = "Toggle Zen Mode" },
    { "<leader>Z", function() require("snacks").zen.zoom() end, desc = "Toggle Zoom" },
  },
}
