#!/usr/bin/env sh
# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0x9fff79ff
yabai -m config normal_window_border_color   0x141416ff
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config debug_output                 off
# yabai -m config split_ratio                  0.50
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# yabai -m config external_bar all:10:0

yabai -m rule --add app="^Google Chrome$" title="^Picture in Picture$" sticky=on
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off

if [[ $OSTYPE == 'darwin'* ]]; then
  osascript -e 'display notification "Yabai Config Loaded" with title "yabairc"'
fi
echo "yabai configuration loaded.."
