#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected="$1" && [[ "$selected" == '.' ]] && selected="$PWD"
else
    selected=$(find ~/work/builds ~/ ~/work ~/personal ~/personal/yt -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

selected_name_t=${selected_name:0:8}

if [[ -n $TMUX ]]; then
  tmux switch-client -t "$selected_name_t" \
  || tmux new-session -ds "$selected_name_t" -c "$selected" \
  && tmux switch-client -t "$selected_name_t"
elif [[ -z $TMUX ]]; then
  tmux new-session -s "$selected_name_t" -c "$selected" \
  || tmux attach -t "$selected_name_t"
fi
