#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected="$1" && [[ "$selected" == '.' ]] && selected="$PWD"
else
    selected=$(find ~/ ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -n $TMUX ]]; then
  tmux switch-client -t "$selected_name" \
  || tmux new-session -ds "$selected_name" -c "$selected" \
  && tmux switch-client -t "$selected_name"
elif [[ -z $TMUX ]]; then
  tmux new-session -s "$selected_name" -c "$selected" \
  || tmux attach -t "$selected_name"
fi
