
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####
export ZSH="$HOME/.oh-my-zsh"
case "$OSTYPE" in
  darwin*)
  ;;
  linux*)
	export PATH="$HOME/neovim/bin:$PATH"
  ;;
esac

ZSH_THEME="robbyrussell"

plugins=(autojump git zsh-autosuggestions fast-syntax-highlighting last-working-dir)

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# SSH Keys
export SSH_KEY_PATH="~/.ssh/id_rsa"

#Alias
alias gg="lazygit"

if command -v bat 1>/dev/null 2>&1; then
	alias cat="bat"
fi

autoload -Uz compinit && compinit

if command -v kitty 1>/dev/null 2>&1; then
	eval "kitty + complete setup zsh | source /dev/stdin"
fi
#FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

## Extra Functions
mkcdir(){
  mkdir -p -- "$1" &&
    cd -P -- "$1"
}

#
# adding pyenv to manage python environments
if command -v pyenv 1>/dev/null 2>&1; then

  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
  alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

fi


export PATH="/usr/local/opt/llvm/bin:/usr/local/opt/luajit-openresty/bin:$PATH"

# path for yarn
export PATH="$(npm bin -g):$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# things for extra support
export DOTFILES="$HOME/.dotfiles"
[ ! -e "$DOTFILES/zsh/extra.sh" ] || \. "$DOTFILES/zsh/extra.sh"
export GPG_TTY=$(tty)

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
