# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
eval "$(fig init zsh pre)"

export ZSH="$HOME/.oh-my-zsh"
case "$OSTYPE" in
  darwin*)
  ;;
  linux*)
	export PATH="$HOME/neovim/bin:$PATH"
  ;;
esac

ZSH_THEME="robbyrussell"

plugins=(autojump git zsh-autosuggestions fast-syntax-highlighting last-working-dir)

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# SSH Keys
export SSH_KEY_PATH="~/.ssh/id_rsa"

#Alias
alias gg="lazygit"

if command -v bat 1>/dev/null 2>&1; then
	alias cat="bat"
fi

autoload -Uz compinit && compinit

if command -v kitty 1>/dev/null 2>&1; then
	eval "kitty + complete setup zsh | source /dev/stdin"
fi
#FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

## Extra Functions
mkcdir(){
  mkdir -p -- "$1" &&
    cd -P -- "$1"
}

. /usr/local/opt/asdf/libexec/asdf.sh

# export LDFLAGS="-L/usr/local/opt/llvm/lib"
# export CPPFLAGS="-I/usr/local/opt/llvm/include"
# export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
# export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"

export PATH="/usr/local/opt/llvm/bin:/usr/local/opt/luajit-openresty/bin:$PATH"
export PATH="$(npm bin -g):$PATH"
export PATH="/usr/local/opt/openssl@3/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# things for extra support
export DOTFILES="$HOME/.dotfiles"
[ ! -e "$DOTFILES/zsh/extra.sh" ] || \. "$DOTFILES/zsh/extra.sh"
export GPG_TTY=$(tty)

# Fig post block. Keep at the bottom of this file.
eval "$(fig init zsh post)"
